version: '3'

services:

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: 'app'
    depends_on:
      - database
      - web
    volumes:
      - ./:/app
    working_dir: /app

  web:
    image: nginx
    container_name: 'web'
    working_dir: /app
    depends_on:
      - database
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  database:
    image: mysql:8.3
    container_name: 'database'
    working_dir: /app
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'source'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - dump

volumes:
  dump:
